[ITC]
enabled = True
hostname = 20.10.0.1
port = 8728
username = GANTI_DENGAN_USERNAME_ITC
password = GANTI_DENGAN_PASSWORD_ITC
use_ssl = False
no_ssl_certificate = True
ssl_certificate_verify = False

installed_packages = True
dhcp = True
dhcp_lease = True
dhcp_pool = True
connections = False
connection_stats = False
interface = True
firewall = True
poe = False
monitor = True
netwatch = False
public_ip = True
route = True
pool = True
system_resources = True
system_health = True
system_routerboard = True
wireless = False
capsman = False
kid_control_devices = False
user = True
queue = True

[GNC]
enabled = True
hostname = ip address
port = port
username = GANTI_DENGAN_USERNAME_GNC
password = GANTI_DENGAN_PASSWORD_GNC
use_ssl = False
no_ssl_certificate = True
ssl_certificate_verify = False

installed_packages = True
dhcp = True
dhcp_lease = True
dhcp_pool = True
connections = False
connection_stats = False
interface = True
firewall = True
poe = False
monitor = True
netwatch = False
public_ip = True
route = True
pool = True
system_resources = True
system_health = True
system_routerboard = True
wireless = False
capsman = False
kid_control_devices = False
user = True
queue = True

[GNC]
enabled = True
hostname = ip   
port = port
username = GANTI_DENGAN_USERNAME_GNC
password = GANTI_DENGAN_PASSWORD_GNC
use_ssl = False
no_ssl_certificate = True
ssl_certificate_verify = False

installed_packages = True
dhcp = True
dhcp_lease = True
dhcp_pool = True
connections = False
connection_stats = False
interface = True
firewall = True
poe = False
monitor = True
netwatch = False
public_ip = True
route = True
pool = True
system_resources = True
system_health = True
system_routerboard = True
wireless = False
capsman = False
kid_control_devices = False
user = True
queue = True
